version: '3.7'

services:
  gatsby:
    container_name: gatsby
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c "while true; do sleep 60; done"
    volumes:
      - .:/app:${CONSISTENCY:-cached}
      - node_modules/:/app/node_modules
      - yarn_cache:/usr/local/cache/yarn/v2
    ports:
      - 8000:8000
volumes:
  node_modules:
    driver: local
  yarn_cache:
    driver: local
