version: 2.1

executors:
  awesome-executor:
    docker:
      - image: circleci/node:12.18.2-stretch
    working_directory: ~/repo

references:
  dependencies_cache_key: &dependencies_cache_key yarn-packages-v1-{{ checksum "yarn.lock" }}
  save_node_modules: &save_node_modules
    save_cache:
      key: *dependencies_cache_key
      paths:
        - node_modules
  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *dependencies_cache_key
        - yarn-packages-v1-

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - install-dependencies-and-lint
      - build:
          requires:
            - install-dependencies-and-lint
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  install-dependencies-and-lint:
    executor: awesome-executor
    steps:
      - checkout
      - *restore_node_modules
      - run: yarn --frozen-lockfile
      - run: yarn lint
      - run: yarn typecheck
      - *save_node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .
  build:
    executor: awesome-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - public/
            - firebase.json
  deploy:
    executor: awesome-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: deploy to firebase
          command: |
            npx firebase-tools deploy \
            --only hosting \
            --token $FIREBASE_DEPLOY_TOKEN \
            --project $FIREBASE_PROJECT
